package emitgo

import (
	"bytes"
	"fmt"
	"go/format"
	"strconv"
	"strings"
	"unicode"

	"github.com/verba-lang/verba/internal/ast"
	"github.com/verba-lang/verba/internal/diagnostic"
)

type emitter struct {
	files       []*ast.File
	buffer      bytes.Buffer
	diagnostics []diagnostic.Diagnostic
	enumCases   map[string]string
	functions   map[string]*ast.Function
	embeds      map[string]*ast.Embed
	temp        int
}

func Files(files []*ast.File) ([]byte, []diagnostic.Diagnostic) {
	e := &emitter{files: files, enumCases: map[string]string{}, functions: map[string]*ast.Function{}, embeds: map[string]*ast.Embed{}}
	for _, file := range files {
		for _, decl := range file.Decls {
			switch value := decl.(type) {
			case *ast.Enum:
				for _, item := range value.Cases {
					e.enumCases[item.Name] = exported(value.Name) + exported(item.Name)
				}
			case *ast.Function:
				e.functions[value.Name] = value
			case *ast.Embed:
				e.embeds[value.Name] = value
			}
		}
	}
	e.validateSupported()
	if diagnostic.HasErrors(e.diagnostics) {
		return nil, e.diagnostics
	}
	e.emitProgram()
	formatted, err := format.Source(e.buffer.Bytes())
	if err != nil {
		e.diagnostics = append(e.diagnostics, diagnostic.Diagnostic{Severity: diagnostic.Error, Code: "VRB3000", File: "<generated>", Line: 1, Column: 1, Message: fmt.Sprintf("generated invalid Go source: %v", err), Hint: "run verba check and report this compiler bug if the source is valid"})
		return e.buffer.Bytes(), e.diagnostics
	}
	return formatted, e.diagnostics
}

func (e *emitter) validateSupported() {
	for _, file := range e.files {
		for _, decl := range file.Decls {
			switch value := decl.(type) {
			case *ast.Function:
				e.validateStatements(value.Body)
			case *ast.Route:
				e.validateStatements(value.Body)
			}
		}
	}
}

func (e *emitter) validateStatements(statements []ast.Stmt) {
	for _, statement := range statements {
		switch value := statement.(type) {
		case *ast.LetStmt:
			e.validateExpr(value.Value)
		case *ast.SetStmt:
			e.validateExpr(value.Value)
		case *ast.ExprStmt:
			e.validateExpr(value.Value)
		case *ast.ReturnStmt:
			if value.Value != nil {
				e.validateExpr(*value.Value)
			}
		case *ast.RespondStmt:
			if value.Value != nil {
				e.validateExpr(*value.Value)
			}
		case *ast.IfStmt:
			e.validateExpr(value.Condition)
			e.validateStatements(value.Then)
			e.validateStatements(value.Else)
		case *ast.ForStmt:
			e.validateExpr(value.Iterable)
			e.validateStatements(value.Body)
		case *ast.WhileStmt:
			e.validateExpr(value.Condition)
			e.validateStatements(value.Body)
		case *ast.MatchStmt:
			e.validateExpr(value.Value)
			for _, matchCase := range value.Cases {
				e.validateExpr(matchCase.Pattern)
				e.validateStatements(matchCase.Body)
			}
			e.validateStatements(value.Else)
		case *ast.TransactionStmt:
			e.error(value.Pos, "VRB3001", "transaction code generation is not available in v0.1.0", "use verba check for SQL validation; database drivers arrive in the next runtime milestone")
		}
	}
}

func (e *emitter) validateExpr(expr ast.Expr) {
	if expr.Kind == ast.ExprCall && strings.HasPrefix(expr.Value, "sql_") {
		e.error(expr.Pos, "VRB3002", "SQL execution code generation is not available in v0.1.0", "SQL islands and bindings can be checked, but build requires an application database adapter")
	}
	for _, arg := range expr.Args {
		e.validateExpr(arg)
	}
	for _, arg := range expr.NamedArgs {
		e.validateExpr(arg.Value)
	}
}

func (e *emitter) emitProgram() {
	e.line(0, "// Code generated by verba 0.1.0. DO NOT EDIT.")
	e.line(0, "package main")
	e.line(0, "")
	e.line(0, `import (`)
	for _, item := range []string{"crypto/rand", "encoding/json", "fmt", "html", "io", "net/http", "os", "regexp", "strings", "time"} {
		e.line(1, "%s", strconv.Quote(item))
	}
	e.line(0, `)`)
	e.line(0, "")
	e.line(0, "var _ = fmt.Sprint")
	e.line(0, "var _ = io.ReadAll")
	e.line(0, "var _ = regexp.MatchString")
	e.line(0, "var _ = strings.TrimSpace")
	e.line(0, "var _ = time.Now")
	e.line(0, "")
	e.line(0, `var templateSlotPattern = regexp.MustCompile(%s)`, strconv.Quote(`\{\{\s*([A-Za-z_][A-Za-z0-9_]*)\s*\}\}`))
	e.line(0, `var uuidPattern = regexp.MustCompile(%s)`, strconv.Quote(`^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$`))
	e.line(0, "")
	e.line(0, "func renderTemplate(source string, values map[string]string, escapeHTML bool) string {")
	e.line(1, "return templateSlotPattern.ReplaceAllStringFunc(source, func(slot string) string {")
	e.line(2, `matches := templateSlotPattern.FindStringSubmatch(slot)`)
	e.line(2, `value := values[matches[1]]`)
	e.line(2, `if escapeHTML { return html.EscapeString(value) }`)
	e.line(2, `return value`)
	e.line(1, "})")
	e.line(0, "}")
	e.line(0, "")
	e.line(0, "type Result[T any, E any] struct {")
	e.line(1, "Value T")
	e.line(1, "Err *E")
	e.line(0, "}")
	e.line(0, "")
	e.line(0, "func decodeJSON[T any](data []byte) Result[T, string] {")
	e.line(1, "var value T")
	e.line(1, "if err := json.Unmarshal(data, &value); err != nil {")
	e.line(2, "message := err.Error()")
	e.line(2, "return Result[T, string]{Err: &message}")
	e.line(1, "}")
	e.line(1, "return Result[T, string]{Value: value}")
	e.line(0, "}")
	e.line(0, "")
	e.line(0, "func newUUID() string {")
	e.line(1, "var value [16]byte")
	e.line(1, "if _, err := rand.Read(value[:]); err != nil { panic(err) }")
	e.line(1, "value[6] = (value[6] & 0x0f) | 0x40")
	e.line(1, "value[8] = (value[8] & 0x3f) | 0x80")
	e.line(1, `return fmt.Sprintf("%%x-%%x-%%x-%%x-%%x", value[0:4], value[4:6], value[6:8], value[8:10], value[10:16])`)
	e.line(0, "}")
	e.line(0, "")
	e.line(0, "func parseUUID(input string) Result[string, string] {")
	e.line(1, "if !uuidPattern.MatchString(input) {")
	e.line(2, `message := "invalid UUID"`)
	e.line(2, "return Result[string, string]{Err: &message}")
	e.line(1, "}")
	e.line(1, "return Result[string, string]{Value: strings.ToLower(input)}")
	e.line(0, "}")
	e.line(0, "")

	for _, file := range e.files {
		for _, decl := range file.Decls {
			switch value := decl.(type) {
			case *ast.Record:
				e.emitRecord(value)
			case *ast.Enum:
				e.emitEnum(value)
			case *ast.Embed:
				if value.Kind == "regex" {
					e.line(0, "var %s = regexp.MustCompile(%s)", safeName(value.Name), strconv.Quote(value.Raw))
				} else {
					e.line(0, "var %s = %s", safeName(value.Name), strconv.Quote(value.Raw))
				}
				e.line(0, "")
			}
		}
	}
	for _, file := range e.files {
		for _, decl := range file.Decls {
			if value, ok := decl.(*ast.Function); ok {
				e.emitFunction(value)
			}
		}
	}
	for _, file := range e.files {
		for _, decl := range file.Decls {
			if value, ok := decl.(*ast.Route); ok {
				e.emitRoute(value)
			}
		}
	}
	e.emitMain()
}

func (e *emitter) emitRecord(record *ast.Record) {
	e.line(0, "type %s struct {", exported(record.Name))
	for _, field := range record.Fields {
		e.line(1, "%s %s `json:%s`", exported(field.Name), goType(field.Type), strconv.Quote(field.Name))
	}
	e.line(0, "}")
	e.line(0, "")
}

func (e *emitter) emitEnum(enum *ast.Enum) {
	name := exported(enum.Name)
	e.line(0, "type %s string", name)
	e.line(0, "")
	e.line(0, "const (")
	for _, item := range enum.Cases {
		e.line(1, "%s%s %s = %s", name, exported(item.Name), name, strconv.Quote(item.Name))
	}
	e.line(0, ")")
	e.line(0, "")
}

func (e *emitter) emitFunction(fn *ast.Function) {
	params := make([]string, 0, len(fn.Inputs))
	for _, input := range fn.Inputs {
		params = append(params, safeName(input.Name)+" "+goType(input.Type))
	}
	result := ""
	if fn.Output != nil {
		result = " " + goType(*fn.Output)
	}
	e.line(0, "func %s(%s)%s {", safeName(fn.Name), strings.Join(params, ", "), result)
	e.emitStatements(fn.Body, 1, fn.Output, false)
	if fn.Output != nil && !blockTerminates(fn.Body) {
		e.line(1, "var zero %s", goType(*fn.Output))
		e.line(1, "return zero")
	}
	e.line(0, "}")
	e.line(0, "")
}

func (e *emitter) emitRoute(route *ast.Route) {
	e.line(0, "func %s(w http.ResponseWriter, r *http.Request) {", safeName(route.Name))
	e.line(1, "request_body, _ := io.ReadAll(r.Body)")
	e.line(1, "_ = request_body")
	e.line(1, "request_headers := r.Header")
	e.line(1, "_ = request_headers")
	e.line(1, "request_context := r.Context()")
	e.line(1, "_ = request_context")
	for _, parameter := range routeParameters(route.Path) {
		e.line(1, "%s := r.PathValue(%s)", safeName(parameter), strconv.Quote(parameter))
	}
	e.emitStatements(route.Body, 1, route.Output, true)
	if !blockTerminates(route.Body) {
		e.line(1, "w.WriteHeader(http.StatusNoContent)")
	}
	e.line(0, "}")
	e.line(0, "")
}

func (e *emitter) emitStatements(statements []ast.Stmt, indent int, output *ast.Type, inRoute bool) {
	for _, statement := range statements {
		switch value := statement.(type) {
		case *ast.LetStmt:
			if value.Value.Try && value.Value.Kind == ast.ExprCall {
				tmp := e.nextTemp()
				expr := value.Value
				expr.Try = false
				e.line(indent, "%s := %s", tmp, e.expr(expr))
				e.line(indent, "if %s.Err != nil {", tmp)
				if inRoute {
					e.line(indent+1, `http.Error(w, fmt.Sprint(*%s.Err), http.StatusInternalServerError)`, tmp)
					e.line(indent+1, "return")
				} else if output != nil && output.Name == "result" {
					errorName := e.nextTemp()
					e.line(indent+1, "%s := *%s.Err", errorName, tmp)
					e.line(indent+1, "return %s{Err: &%s}", goType(*output), errorName)
				} else {
					e.line(indent+1, "panic(fmt.Sprint(*%s.Err))", tmp)
				}
				e.line(indent, "}")
				e.line(indent, "%s := %s.Value", safeName(value.Name), tmp)
				e.line(indent, "_ = %s", safeName(value.Name))
			} else {
				e.line(indent, "%s := %s", safeName(value.Name), e.expr(value.Value))
				e.line(indent, "_ = %s", safeName(value.Name))
			}
		case *ast.SetStmt:
			path := make([]string, len(value.Path))
			for i, part := range value.Path {
				if i == 0 {
					path[i] = safeName(part)
				} else {
					path[i] = exported(part)
				}
			}
			e.line(indent, "%s = %s", strings.Join(path, "."), e.expr(value.Value))
		case *ast.ExprStmt:
			e.line(indent, "%s", e.expr(value.Value))
		case *ast.ReturnStmt:
			if value.Value == nil {
				e.line(indent, "return")
			} else if output != nil && output.Name == "result" && value.Value.Kind == ast.ExprCall && (value.Value.Value == "ok" || value.Value.Value == "error") {
				e.emitResultReturn(*value.Value, *output, indent)
			} else {
				e.line(indent, "return %s", e.expr(*value.Value))
			}
		case *ast.RespondStmt:
			e.emitRespond(value, indent)
		case *ast.IfStmt:
			e.line(indent, "if %s {", e.expr(value.Condition))
			e.emitStatements(value.Then, indent+1, output, inRoute)
			if len(value.Else) > 0 {
				e.line(indent, "} else {")
				e.emitStatements(value.Else, indent+1, output, inRoute)
			}
			e.line(indent, "}")
		case *ast.ForStmt:
			e.line(indent, "for _, %s := range %s {", safeName(value.Name), e.expr(value.Iterable))
			e.emitStatements(value.Body, indent+1, output, inRoute)
			e.line(indent, "}")
		case *ast.WhileStmt:
			e.line(indent, "for %s {", e.expr(value.Condition))
			e.emitStatements(value.Body, indent+1, output, inRoute)
			e.line(indent, "}")
		case *ast.MatchStmt:
			e.line(indent, "switch %s {", e.expr(value.Value))
			for _, matchCase := range value.Cases {
				e.line(indent, "case %s:", e.expr(matchCase.Pattern))
				e.emitStatements(matchCase.Body, indent+1, output, inRoute)
			}
			if len(value.Else) > 0 {
				e.line(indent, "default:")
				e.emitStatements(value.Else, indent+1, output, inRoute)
			}
			e.line(indent, "}")
		}
	}
}

func (e *emitter) emitResultReturn(expr ast.Expr, output ast.Type, indent int) {
	typeName := goType(output)
	value := "nil"
	if len(expr.Args) > 0 {
		value = e.expr(expr.Args[0])
	}
	if expr.Value == "ok" {
		e.line(indent, "return %s{Value: %s}", typeName, value)
		return
	}
	tmp := e.nextTemp()
	e.line(indent, "%s := %s", tmp, value)
	e.line(indent, "return %s{Err: &%s}", typeName, tmp)
}

func (e *emitter) emitRespond(stmt *ast.RespondStmt, indent int) {
	switch stmt.Format {
	case "json":
		e.line(indent, `w.Header().Set("Content-Type", "application/json; charset=utf-8")`)
		e.line(indent, "w.WriteHeader(%d)", stmt.Status)
		if stmt.Value != nil {
			e.line(indent, "_ = json.NewEncoder(w).Encode(%s)", e.expr(*stmt.Value))
		}
	case "empty":
		e.line(indent, "w.WriteHeader(%d)", stmt.Status)
	default:
		e.line(indent, `w.Header().Set("Content-Type", "text/plain; charset=utf-8")`)
		e.line(indent, "w.WriteHeader(%d)", stmt.Status)
		if stmt.Value != nil {
			e.line(indent, "_, _ = io.WriteString(w, %s)", e.expr(*stmt.Value))
		}
	}
	e.line(indent, "return")
}

func (e *emitter) expr(expr ast.Expr) string {
	switch expr.Kind {
	case ast.ExprText:
		return strconv.Quote(expr.Value)
	case ast.ExprAtom:
		if enum, exists := e.enumCases[expr.Value]; exists {
			return enum
		}
		return safeName(expr.Value)
	case ast.ExprGet:
		parts := make([]string, 0, len(expr.Args))
		for i, arg := range expr.Args {
			if i == 0 {
				parts = append(parts, safeName(arg.Value))
			} else {
				parts = append(parts, exported(arg.Value))
			}
		}
		return strings.Join(parts, ".")
	case ast.ExprRelation:
		op := "=="
		if expr.Not {
			op = "!="
		}
		return fmt.Sprintf("(%s %s %s)", e.expr(expr.Args[0]), op, e.expr(expr.Args[1]))
	case ast.ExprCall:
		return e.call(expr)
	default:
		return "nil"
	}
}

func (e *emitter) call(expr ast.Expr) string {
	args := make([]string, 0, len(expr.Args))
	for _, arg := range expr.Args {
		args = append(args, e.expr(arg))
	}
	if fn := e.functions[expr.Value]; fn != nil && len(expr.NamedArgs) > 0 {
		named := map[string]ast.Expr{}
		for _, arg := range expr.NamedArgs {
			named[arg.Name] = arg.Value
		}
		args = args[:0]
		for _, input := range fn.Inputs {
			args = append(args, e.expr(named[input.Name]))
		}
	}
	switch expr.Value {
	case "add":
		return "(" + args[0] + " + " + args[1] + ")"
	case "subtract":
		return "(" + args[0] + " - " + args[1] + ")"
	case "multiply":
		return "(" + args[0] + " * " + args[1] + ")"
	case "divide":
		return "(" + args[0] + " / " + args[1] + ")"
	case "remainder":
		return "(" + args[0] + " % " + args[1] + ")"
	case "negate":
		return "(-" + args[0] + ")"
	case "greater_than":
		return "(" + args[0] + " > " + args[1] + ")"
	case "less_than":
		return "(" + args[0] + " < " + args[1] + ")"
	case "greater_equal":
		return "(" + args[0] + " >= " + args[1] + ")"
	case "less_equal":
		return "(" + args[0] + " <= " + args[1] + ")"
	case "and":
		return "(" + args[0] + " && " + args[1] + ")"
	case "or":
		return "(" + args[0] + " || " + args[1] + ")"
	case "not":
		return "(!" + args[0] + ")"
	case "trim":
		return "strings.TrimSpace(" + args[0] + ")"
	case "lowercase":
		return "strings.ToLower(" + args[0] + ")"
	case "uppercase":
		return "strings.ToUpper(" + args[0] + ")"
	case "contains":
		return "strings.Contains(" + args[0] + ", " + args[1] + ")"
	case "starts_with":
		return "strings.HasPrefix(" + args[0] + ", " + args[1] + ")"
	case "concat":
		return "strings.Join([]string{" + strings.Join(args, ", ") + "}, \"\")"
	case "new_uuid":
		return "newUUID()"
	case "parse_uuid":
		return "parseUUID(" + args[0] + ")"
	case "regex_match":
		if len(expr.Args) == 2 {
			if embed := e.embeds[expr.Args[0].Value]; embed != nil && embed.Kind == "regex" {
				return args[0] + ".MatchString(" + args[1] + ")"
			}
		}
		return "func() bool { ok, _ := regexp.MatchString(" + args[0] + ", " + args[1] + "); return ok }()"
	case "json_decode":
		if len(expr.Args) == 2 {
			return "decodeJSON[" + exported(expr.Args[0].Value) + "](" + args[1] + ")"
		}
	case "json_encode":
		return "func() []byte { data, _ := json.Marshal(" + args[0] + "); return data }()"
	case "is_some":
		return "(" + args[0] + " != nil)"
	case "is_none":
		return "(" + args[0] + " == nil)"
	case "unwrap":
		return "(*" + args[0] + ")"
	case "render":
		values := make([]string, 0, len(expr.NamedArgs))
		for _, arg := range expr.NamedArgs {
			values = append(values, strconv.Quote(arg.Name)+": "+e.expr(arg.Value))
		}
		escapeHTML := "false"
		if len(expr.Args) > 0 {
			if embed := e.embeds[expr.Args[0].Value]; embed != nil && embed.Kind == "html" {
				escapeHTML = "true"
			}
		}
		return "renderTemplate(" + args[0] + ", map[string]string{" + strings.Join(values, ", ") + "}, " + escapeHTML + ")"
	}
	return safeName(expr.Value) + "(" + strings.Join(args, ", ") + ")"
}

func (e *emitter) emitMain() {
	e.line(0, "func main() {")
	e.line(1, "mux := http.NewServeMux()")
	count := 0
	for _, file := range e.files {
		for _, decl := range file.Decls {
			if route, ok := decl.(*ast.Route); ok {
				pattern := strings.ToUpper(route.Method) + " " + route.Path
				e.line(1, "mux.HandleFunc(%s, %s)", strconv.Quote(pattern), safeName(route.Name))
				count++
			}
		}
	}
	if count == 0 {
		e.line(1, `mux.HandleFunc("GET /", func(w http.ResponseWriter, _ *http.Request) { _, _ = io.WriteString(w, "Verba program is running") })`)
	}
	e.line(1, `address := os.Getenv("VERBA_ADDRESS")`)
	e.line(1, `if address == "" { address = ":8080" }`)
	e.line(1, `fmt.Printf("Verba server listening on %%s\n", address)`)
	e.line(1, "if err := http.ListenAndServe(address, mux); err != nil { panic(err) }")
	e.line(0, "}")
}

func goType(t ast.Type) string {
	switch t.Name {
	case "bool", "string", "int", "uint", "int8", "int16", "int32", "int64", "uint8", "uint16", "uint32", "uint64", "float32", "float64":
		return t.Name
	case "bytes":
		return "[]byte"
	case "decimal":
		return "float64"
	case "uuid", "url", "path":
		return "string"
	case "time":
		return "time.Time"
	case "duration":
		return "time.Duration"
	case "optional":
		return "*" + goType(t.Args[0])
	case "list":
		return "[]" + goType(t.Args[0])
	case "map":
		return "map[" + goType(t.Args[0]) + "]" + goType(t.Args[1])
	case "result":
		return "Result[" + goType(t.Args[0]) + ", " + goType(t.Args[1]) + "]"
	default:
		return exported(t.Name)
	}
}

func exported(value string) string {
	parts := strings.Split(value, "_")
	for i, part := range parts {
		if part == "" {
			continue
		}
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		parts[i] = string(runes)
	}
	return strings.Join(parts, "")
}

func safeName(value string) string {
	if value == "true" || value == "false" || isNumber(value) {
		return value
	}
	reserved := map[string]bool{"break": true, "default": true, "func": true, "interface": true, "select": true, "case": true, "defer": true, "go": true, "map": true, "struct": true, "chan": true, "else": true, "goto": true, "package": true, "switch": true, "const": true, "fallthrough": true, "if": true, "range": true, "type": true, "continue": true, "for": true, "import": true, "return": true, "var": true}
	if reserved[value] {
		return value + "Value"
	}
	return value
}

func isNumber(value string) bool {
	if _, err := strconv.ParseInt(value, 10, 64); err == nil {
		return true
	}
	_, err := strconv.ParseFloat(value, 64)
	return err == nil
}

func routeParameters(path string) []string {
	var result []string
	for {
		start := strings.IndexByte(path, '{')
		if start < 0 {
			return result
		}
		end := strings.IndexByte(path[start+1:], '}')
		if end < 0 {
			return result
		}
		result = append(result, path[start+1:start+1+end])
		path = path[start+1+end+1:]
	}
}

func blockTerminates(statements []ast.Stmt) bool {
	if len(statements) == 0 {
		return false
	}
	switch value := statements[len(statements)-1].(type) {
	case *ast.ReturnStmt, *ast.RespondStmt:
		return true
	case *ast.IfStmt:
		return len(value.Else) > 0 && blockTerminates(value.Then) && blockTerminates(value.Else)
	case *ast.MatchStmt:
		if len(value.Else) == 0 || !blockTerminates(value.Else) {
			return false
		}
		for _, matchCase := range value.Cases {
			if !blockTerminates(matchCase.Body) {
				return false
			}
		}
		return len(value.Cases) > 0
	default:
		return false
	}
}

func (e *emitter) nextTemp() string { e.temp++; return fmt.Sprintf("verbaTemp%d", e.temp) }
func (e *emitter) line(indent int, format string, args ...any) {
	e.buffer.WriteString(strings.Repeat("\t", indent))
	fmt.Fprintf(&e.buffer, format, args...)
	e.buffer.WriteByte('\n')
}
func (e *emitter) error(pos ast.Position, code, message, hint string) {
	e.diagnostics = append(e.diagnostics, diagnostic.Diagnostic{Severity: diagnostic.Error, Code: code, File: pos.File, Line: pos.Line, Column: pos.Column, Message: message, Hint: hint})
}
